version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  # Keep Homebrew Brewfile up to date (informational, as Brewfile is not natively supported, but can be tracked for changes)
  - package-ecosystem: "bundler"
    directory: "/config/brew/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
