/**
 * dsh-web-search-ddgs — local DuckDuckGo search provider for the harness.
 *
 * Host-plane row. Registers the `ddgs-local` WebSearchProvider in `ctx.web`,
 * running the user's Python DDGS bridge (`execute_local_search`) through a
 * local subprocess. The profile's cordis.patch.yml pins
 * `web.searchProvider: ddgs-local`, so the model-facing `web_search` tool
 * executes every search entirely on this machine.
 *
 * Layout (all self-contained under this package directory):
 *   venv/            virtualenv with duckduckgo-search installed
 *   index.js         this plugin
 *
 * The venv is created on first apply if missing (needs network for pip).
 */
'use strict'

const { existsSync } = require('node:fs')
const { join } = require('node:path')

const PLUGIN_DIR = __dirname
const VENV_DIR = join(PLUGIN_DIR, 'venv')
const VENV_PYTHON = join(VENV_DIR, 'bin', 'python3')
// Base interpreter used to create the venv (mise-managed Python 3.14).
const BASE_PYTHON = '/Users/akle/.local/share/mise/installs/python/3.14.6/bin/python3'

/**
 * The user's bridge, verbatim. Fed to `python -` via stdin (the program),
 * with the JSON `{ "query": ... }` argument in argv[1]. The f-string
 * `\n` escapes are doubled here so the emitted Python source keeps them.
 */
const PYTHON_SOURCE = `import json
import sys
from duckduckgo_search import DDGS

def execute_local_search(arguments_str):
    """Executes a DuckDuckGo search entirely from your local machine."""
    try:
        # Parse the query generated by the DeepSeek model
        args = json.loads(arguments_str)
        query = args.get("query", "")

        if not query:
            return "Error: Empty search query."

        # Execute the search locally via your own internet connection
        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=3))

        # Format the results so the harness can feed them back to the model
        formatted_results = []
        for r in results:
            formatted_results.append(
                f"Title: {r['title']}\\nURL: {r['href']}\\nSnippet: {r['body']}"
            )
        return "\\n\\n".join(formatted_results)

    except Exception as e:
        return f"Local search pipeline execution failed: {str(e)}"

print(execute_local_search(sys.argv[1]))
`

/** Extract one `Key: value` line from a bridge result block. */
function matchLine(block, key) {
  const match = block.match(new RegExp('^' + key + ':\\s*(.*)$', 'm'))
  return match === null ? undefined : match[1].trim()
}

/** Parse the bridge's stable `Title:/URL:/Snippet:` text into web sources. */
function parseBridgeOutput(text) {
  const sources = []
  const seen = new Set()
  for (const block of String(text).split(/\n\s*\n+/)) {
    const title = matchLine(block, 'Title')
    const url = matchLine(block, 'URL')
    const snippet = matchLine(block, 'Snippet')
    if (url === undefined || seen.has(url)) continue
    seen.add(url)
    sources.push({
      url,
      ...(title !== undefined ? { title } : {}),
      ...(snippet !== undefined ? { snippet } : {})
    })
  }
  return sources
}

/** Run one local DDGS search through the bridge subprocess. */
function runLocalSearch(subprocess, query, signal) {
  const handle = subprocess.spawn({
    argv: [VENV_PYTHON, '-', JSON.stringify({ query })],
    cwd: PLUGIN_DIR,
    stdio: {
      stdin: { data: PYTHON_SOURCE },
      stdout: { maxBytes: 64 * 1024, spill: { maxBytes: 256 * 1024 } },
      stderr: { maxBytes: 32 * 1024 }
    },
    graceMs: 2000,
    ...(signal !== undefined ? { signal } : {})
  })
  return handle.done.then((outcome) => {
    const stdout = handle.collected.stdout.readFrom(0).text
    const stderr = handle.collected.stderr.readFrom(0).text
    if (outcome.exitCode !== 0) {
      throw new Error('ddgs-bridge: local search process failed' + (stderr.trim() !== '' ? ': ' + stderr.trim() : ''))
    }
    const text = stdout.trim()
    if (text.startsWith('Error:') || text.startsWith('Local search pipeline execution failed')) {
      throw new Error('ddgs-bridge: ' + text)
    }
    return parseBridgeOutput(text)
  })
}

/** Create the venv and install duckduckgo-search when the bridge is missing it. */
async function ensureVenv(subprocess) {
  if (existsSync(VENV_PYTHON)) return true
  const create = subprocess.spawn({
    argv: [BASE_PYTHON, '-m', 'venv', VENV_DIR],
    cwd: PLUGIN_DIR,
    stdio: { stdin: 'ignore', stdout: { maxBytes: 64 * 1024 }, stderr: { maxBytes: 64 * 1024 } },
    graceMs: 2000
  })
  const created = await create.done
  if (created.exitCode !== 0) {
    const detail = create.collected.stderr.readFrom(0).text.trim() || create.collected.stdout.readFrom(0).text.trim()
    throw new Error('ddgs-bridge: venv creation failed' + (detail !== '' ? ': ' + detail : ''))
  }
  const install = subprocess.spawn({
    argv: [VENV_PYTHON, '-m', 'pip', 'install', '--quiet', 'duckduckgo-search'],
    cwd: PLUGIN_DIR,
    stdio: { stdin: 'ignore', stdout: { maxBytes: 64 * 1024 }, stderr: { maxBytes: 64 * 1024 } },
    graceMs: 2000
  })
  const installed = await install.done
  if (installed.exitCode !== 0) {
    const detail = install.collected.stderr.readFrom(0).text.trim() || install.collected.stdout.readFrom(0).text.trim()
    throw new Error('ddgs-bridge: pip install failed' + (detail !== '' ? ': ' + detail : ''))
  }
  return true
}

module.exports = {
  name: 'web-search-ddgs',
  inject: ['web', 'subprocess'],
  apply(ctx) {
    const web = ctx.get('web')
    const subprocess = ctx.get('subprocess')
    if (web === undefined || subprocess === undefined) {
      console.error('[web-search-ddgs] web or subprocess service unavailable; provider NOT registered')
      return
    }

    // Make sure the bridge environment exists, then prove the whole chain.
    ensureVenv(subprocess)
      .then(() => runLocalSearch(subprocess, 'DeepSeek harness', undefined))
      .then((sources) => console.log(`[web-search-ddgs] bridge ready — self-test parsed ${sources.length} source(s)`))
      .catch((error) => console.error(`[web-search-ddgs] bridge setup/self-test failed: ${String(error)}`))

    web.registerSearchProvider({
      id: 'ddgs-local',
      available() {
        return existsSync(VENV_PYTHON)
      },
      async search(request, signal) {
        const sources = await runLocalSearch(subprocess, request.query, signal)
        return { sources, truncated: false }
      }
    })
    console.log('[web-search-ddgs] registered ddgs-local search provider')
  },

  // Exported for smoke testing; the loader only reads name/inject/apply.
  parseBridgeOutput,
  runLocalSearch,
  PYTHON_SOURCE,
  VENV_PYTHON
}
