# mise configuration
# See: https://mise.jdx.dev/configuration.html

[tools]
gitleaks = "latest"
go = "latest"
gradle = "8.14.0"
helm = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
lefthook = "latest"
neovim = "latest"
node = "22"
python = "latest"
rust = "latest"

[settings]
experimental = true
