# mise configuration
# See: https://mise.jdx.dev/configuration.html

[tools]
python = "3.12"
node = "22"
go = "latest"
rust = "latest"
kubectl = "latest"
helm = "latest"

[settings]
experimental = true

[env]
# Virtual environment config
_.python.venv = { path = ".venv", create = true }
