# mise configuration
# See: https://mise.jdx.dev/configuration.html

[tools]
adr-tools = "latest"
age = "latest"
gitleaks = "latest"
go = "latest"
gradle = "8.14.0"
helm = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
lefthook = "latest"
neovim = "latest"
node = "latest"
python = "latest"
rust = "latest"
sops = "latest"

[settings]
experimental = true

[env]
MISE_NODE_DEFAULT_PACKAGES_FILE = '$XDG_CONFIG_HOME/mise/.default-npm-packages'
