# mise configuration
# See: https://mise.jdx.dev/configuration.html

[tools]
python = "3.12"
node = "22"
go = "latest"
rust = "latest"
gradle = "8.14.0"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
helm = "latest"
lefthook = "latest"

[settings]
experimental = true
